version: "1.0"
info:
  model: int-scaffold
packages:
- name: CsinTest1Project
  gitServerName: csinTest
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: GithubPackageDebuglog
  gitServerName: csinTest
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: substractpackage
  gitServerName: csinGit
  gitUrl: https://gitlab.com/ArtiKhareGitlabnew
  gitUsername: ArtiKhareGitlabnew
  gitBranch: master
